Fix build against `gcc-13` (missing `<cstdint>` includes)
Without the change build fails against `gcc-13` as:

    /build/source/src/conversion/autocorrelation_to_composite_sinusoidal_modeling.cc:25:1: error: 'uint64_t' does not name a type
       25 | uint64_t CalculateBinomialCoefficient(int n, int k) {
          | ^~~~~~~~
    /build/source/src/conversion/autocorrelation_to_composite_sinusoidal_modeling.cc:21:1: note: 'uint64_t' is defined in header '<cstdint>'; did you forget to '#include <cstdint>'?
       20 | #include <cmath>      // std::acos, std::fabs, std::pow
      +++ |+#include <cstdint>
       21 | #include <cstddef>    // std::size_t